### ISSUE TITLE
TGM v0.2.0 Roadmap

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#28]
This is the **roadmap for torchgeometry v0.2.0** focuses mainly importing [GVNN](https://github.com/ankurhanda/gvnn), documentation improvement and website. Some basic functionalities for image processing will also be part of this release.

Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list). Please, take a read on the **[CONTRIBUTING](https://github.com/arraiyopensource/torchgeometry/blob/master/CONTRIBUTING.rst)** notes.

- **GVNN**
  - Linear Transformations
    - [x] relative_pose 6130892e596eba9511aaa752db84f7369be6de58
  - SO3 Layer [[link](https://github.com/ankurhanda/gvnn#so3-layer)]
    - [ ] TransformationRotationSO3
    - [ ] Transform3DPoints_R
  - SE3 Layer [[link](https://github.com/ankurhanda/gvnn#se3-layer)]
    - [ ] TransformationMatrix3x4SO3
    - [ ] Transform3DPoints_Rt
  - Common
    - [ ] PinHoleCameraProjectionBHWD
    - [ ] ReverseXYOrder
  - Optical Flow [[link](https://github.com/ankurhanda/gvnn#optical-flow)]
  - Disparity [[link](https://github.com/ankurhanda/gvnn#disparity)]
  - Projection Layer [[link](https://github.com/ankurhanda/gvnn#projection-layer)]
  - Lens Distorsion [[link](https://github.com/ankurhanda/gvnn#lens-distortion)]
  - Nonrigid SO3 [[link](https://github.com/ankurhanda/gvnn#nonrigid-so3)]
  - Nonrigid SE3 [[link](https://github.com/ankurhanda/gvnn#nonrigid-se3)]
  - M-estimators [[link](https://github.com/ankurhanda/gvnn#nonrigid-se3)]
- **LAF: Local Affine Features**
  - [ ] CornersHarris @edgarriba
- **Image Filtering**
  - [x] GaussianBlur 0ff6f5e070a34a5eca4ba0b801cf375c4c1f9af9 
  - [ ] Blur
  - [ ] PyrDown  @edgarriba 
  - [ ] Sobel  @edgarriba 
- **Image Color Space**: borrowed from _tf.image_
  - [ ] rgb_to_grayscale
  - [ ] hsv_to_rgb
  - [ ] rgb_to_hsv
  - [ ] rgb_to_yiq
  - [ ] rgb_to_yuv
  - [ ] yiq_to_rgb
  - [ ] yuv_to_rgb
- **Contrib**
  - [x] SpatialSoftArgmax2d cf7bb292dbe19242e0b207a8747da601a27e4cf3
  - [ ] ROIAlign @IssamLaradji
  - [ ] SoftArgmax
- **Losses**
  - [x] SSIM 7f890f494b47ed4dd0414a0d6f45cf5d22809d69
  - [x] DepthSmoothnessLoss 42a1d22df0691444664c182eae7fc10acaa428cc
  - [x] DiceLoss 9b0fddf9055cb9a948856d087b52073551c44129
  - [x] TverskyLoss 89246d269739f89ed0731f52ff543863882efa48
  - [x] FocalLoss ffe4cb1b74ecb81baef05f97fe6c62f176336fd7
  - [ ] MultiScaleSSIM
  - [ ] PSNR
- **Metrics**
  - [x] ConfusionMatrix 3678dcfe5cb456647dcf52b7925f7a42543349eb
  - [x] MeanIoU 3678dcfe5cb456647dcf52b7925f7a42543349eb
- **Installation**
  - [ ] conda packages
- **Documentation**
  - [x] create CONTRIBUTING file 0ab5c8a373614d065551ea6fa81fd80615c41601
  - [x] add tutorials to sphinx docs 06bdd0382590ecd6eae576b1cfad8f0aeaf49718
  - [x] add examples to sphinx docs 39eb046f36e6dba457eb6195165c22d58db68e43
  - [ ] create front-end website
  - [ ] add installation and extended project background to website
  - [ ] fix jupyter notebooks tracebacks
- **Test**
  - [x] add pytest-cov and Codecov check to CI 909b529cd0df17fd705068a9050e10d416e74896
  - [x] add mypy check to CI 6cbaef37382e9eaf74d5393c75bea0c8ce058591
  - [x] add docs to readthedocs dbfaa1a43e231fdc250ca3ddeba1a79a6971ba0d
  - [ ] refactor test framework. Goal: designing proper classes @carlosb1 https://github.com/arraiyopensource/torchgeometry/issues/38
  - [ ] CUDA tests (looking for alternatives for GPU servers with Jenkins)
- **Tutorials**
  - [ ] add code to CI
  - *Beginner*
    - [ ] improve rotation tutorial with extra explanation, add batched version.
    - [ ] improve perspective tutorial with extra explanation, add batched version.
    - [ ] improve gaussian blur tutorial with extra explanation, add batched version.
    - [ ] add sobel tutorial
    - [ ] add box blur, pyrdown tutorial
  - *Intermediate*
    - [ ] add pipeline example: use sequential to implement vision pipelines.
    - [ ] add JIT tutorial
  - *Advanced*
    - [ ] move existing homography tutorial to docs
    - [ ] move existing depth tutorial to docs
    - [ ] add SSIM example to learn input image

**Comment by edgarriba** [comment]
@ankurhanda What do you think we should prioritize for importing GVNN ? You mention that you have already some ported codes. Might be helpful if you could give a brief list of ideas of what do you already have and not.

**Comment by ankurhanda** [comment]
This is what I have already now. 
- SO3
- SE3 
- Non-rigid SE3 
- Projection Layer 
- Depth Estimation

**Comment by edgarriba** [comment]
closing this since this roadmap is deprecated.

Will create new one very soon since the target of the library is more generic computer vision, not only geometry. See package renaming to "kornia": cdd8f01f5ff6e1c7ac68b47137f0f77bd671ba4d
